name: Pages_Directory_Listing
on: [ push ]

jobs:

  # Job 1. List the pages and generate the artifact
  pages_directory_listing:

    runs-on: ubuntu-latest
    name: Pages Directory Listing

    steps:

      # Step 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # branch to check out
          ref: main

      # Step 2. Generate the artifact
      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v3.0.0
        with:
          # directory to generate the artifact
          FOLDER: .

      # Step 3. Upload the artifact
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

  # Job 2. Deploy the artifact
  deploy:

    needs: pages_directory_listing
    
    runs-on: ubuntu-latest
    name: Deploy
    
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # Step 1. Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1